---

- name: Nginx | RedHat | Installing nginx
  include_tasks: RedHat/install.yml
  when:
    - nginxRedHatPackageName not in ansible_facts.packages

- name: Nginx | RedHat | Configure nginx
  include_tasks: RedHat/configure.yml
  when:
    - nginxRedHatPackageName in ansible_facts.packages
