---

- name: Nginx | Debian | Install required packages
  apt:
    name: "{{ item }}"
    state: present
    update_cache: true
  loop:
    - "{{ nginxDebianPackages }}"

- name: Nginx | Debian | Place Nginx repo file
  template:
    src: "{{ nginxDebianRepoSource }}"
    dest: "{{ nginxDebianRepoDestination }}"
  when: ansible_distribution == 'Debian'

- name: Nginx | Ubuntu | Place Nginx repo file
  template:
    src: "{{ nginxUbuntuRepoSource }}"
    dest: "{{ nginxUbuntuRepoDestination }}"
  when: ansible_distribution == 'UBuntu'

- name: Nginx | Debian | Place Nginx priority file
  template:
    src: "{{ nginxDebianPriorityFileSource }}"
    dest: "{{ nginxDebianPriorityFileDestination }}"

#- name: Nginx | Debian | Get GPG key
#  get_url:
#    url: "{{ nginxDebianGPGKeyUrl }}"
#    dest: "{{ nginxDebianGPGKeyLocation }}"
#
#- name: Nginx | Debian | Install GPG Key
#  shell: "gpg --quiet --import --import-options import-show {{ nginxDebianGPGKeyLocation }}"

- name: Nginx | Debian | Get and Install GPG Key
  shell: "curl {{ nginxDebianGPGKeyUrl }} | gpg --dearmor | tee {{ nginxDebianGPGKeyLocation }} >/dev/null"

- name: Nginx | Debian | Installing nginx
  apt:
    name: "{{ nginxDebianPackageName }}"
    state: present
    update_cache: true

# initial start of nginx for file creation
- name: Nginx | Debian | Initial Startup
  systemd:
    name: "nginx.service"
    state: "started"

- name: Nginx | Debian | Configure nginx
  include_tasks: Debian/configure.yml
