---

- name: Nginx | Redhat | Place custom nginx file
  template:
    src: "{{ nginxRedHatNginxTemplateSource }}"
    dest: "{{ nginxRedHatNginxTemplateDestination }}"
  notify:
    - nginxRedHatHandler
